import { API_DOCTOR_PATHS } from "./api.routes";

////////////////////////////////// USER ENDPOINTS
const DOCTORSLANDINGPAGE = `${API_DOCTOR_PATHS.DOCTORSLANDINGPAGE}`;
const GETDOCTOR = `${API_DOCTOR_PATHS.GETDOCTOR}`;
const GETALLDOCTORS = `${API_DOCTOR_PATHS.GETALLDOCTORS}`;
const GETDOCTORAVAILABLEDAYSLOTS = `${API_DOCTOR_PATHS.GETDOCTORAVAILABLEDAYSLOTS}`;

export {
  DOCTORSLANDINGPAGE,
  GETDOCTOR,
  GETALLDOCTORS,
  GETDOCTORAVAILABLEDAYSLOTS,
};
