import { API_AUTH_PATHS } from "./api.routes";

/////////////////////////////// AUTHENTICATION ENDPOINTS
const SIGNUP = `${API_AUTH_PATHS.SIGNUP}`;
const LOGIN = `${API_AUTH_PATHS.LOGIN}`;
const VERIFICATION = `${API_AUTH_PATHS.VERIFICATION}`;
const RESENDVERIFICATIONCODE = `${API_AUTH_PATHS.RESENDVERIFICATIONCODE}`;
const REFRESHTOKEN = `${API_AUTH_PATHS.REFRESHTOKEN}`;
const CLEARACCESSTOKEN = `${API_AUTH_PATHS.CLEARACCESSTOKEN}`;
const VALIDATETOKEN = `${API_AUTH_PATHS.VALIDATETOKEN}`;

export {
  SIGNUP,
  LOGIN,
  VERIFICATION,
  RESENDVERIFICATIONCODE,
  REFRESHTOKEN,
  CLEARACCESSTOKEN,
  VALIDATETOKEN,
};
