import { API_SUGGESTION_PATHS } from "./api.routes";

////////////////////////////////// USER ENDPOINTS
const GETSEARCHSUGGESTIONS = `${API_SUGGESTION_PATHS.GETSEARCHSUGGESTIONS}`;
const SAVESEARCHSUGGESTION = `${API_SUGGESTION_PATHS.SAVESEARCHSUGGESTION}`;

export { GETSEARCHSUGGESTIONS, SAVESEARCHSUGGESTION };
