import { API_USER_PATHS } from "./api.routes";

////////////////////////////////// USER ENDPOINTS
const FORGOTPASSWORD = `${API_USER_PATHS.FORGOTPASSWORD}`;
const RESETPASSWORD = `${API_USER_PATHS.RESETPASSWORD}`;
const FETCHUSER = `${API_USER_PATHS.FETCHUSER}`;

export { FORGOTPASSWORD, RESETPASSWORD, FETCHUSER };
